### ISSUE TITLE
It is not possible to convert files including pictures.

### ISSUE THREAD

**Issue by jam7** [jam7/narou-docker-alpine#1]
AozoraEpub3 is using [JAI (Java Advanced Imaging) API](http://www.oracle.com/technetwork/java/javasebusiness/downloads/java-archive-downloads-java-client-419417.html#jai-1_1_2_01-oth-JPR), but it is not available in OpenJDK.

JAI uses com.sun.image.codec.jpeg, but it is removed from Java7 as menthioned here, http://www.oracle.com/technetwork/java/javase/compatibility-417013.html.

As a result, it shows following error.
```
変換開始 : /opt/narou/小説データ/小説家になろう/n6316bn 転生したらスライムだった件/[伏瀬] 転生したらスライムだった件.txt
java.io.IOException: This archives contains unclosed entries.
        at org.apache.commons.compress.archivers.zip.ZipArchiveOutputStream.finish(ZipArchiveOutputStream.java:343)
        at org.apache.commons.compress.archivers.zip.ZipArchiveOutputStream.close(ZipArchiveOutputStream.java:550)
        at com.github.hmdev.writer.Epub3Writer.write(Epub3Writer.java:968)
        at AozoraEpub3.convertFile(AozoraEpub3.java:512)
        at AozoraEpub3.main(AozoraEpub3.java:431)
Exception in thread "main" java.lang.NoClassDefFoundError: com/sun/image/codec/jpeg/ImageFormatException
        at com.sun.media.jai.codecimpl.JPEGImageDecoder.decodeAsRenderedImage(JPEGImageDecoder.java:46)
        at com.sun.media.jai.codec.ImageDecoderImpl.decodeAsRenderedImage(ImageDecoderImpl.java:140)
        at com.github.hmdev.image.ImageUtils.readImage(ImageUtils.java:107)
        at com.github.hmdev.image.ImageUtils.writeImage(ImageUtils.java:152)
        at com.github.hmdev.writer.Epub3Writer.writeImage(Epub3Writer.java:1032)
        at com.github.hmdev.writer.Epub3Writer.write(Epub3Writer.java:909)
        at AozoraEpub3.convertFile(AozoraEpub3.java:512)
        at AozoraEpub3.main(AozoraEpub3.java:431)
Caused by: java.lang.ClassNotFoundException: com.sun.image.codec.jpeg.ImageFormatException
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        ... 8 more
pid 8 exit 1
[ERROR] JavaがインストールされていないかAozoraEpub3実行時にエラーが発生しました。EPUBを作成出来ませんでした
```

**Comment by jam7** [comment]
Fixed this problem at https://github.com/jam7/AozoraEpub3/tree/openjdk-support and send PR to official site.
